version: '3'
services:
  chassis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/Chassis:cached
    working_dir: /workspaces/Chassis
    tty: true
    command: [scripts/server-start.bash]
    ports:
      - 8000:8000
