name: Create Release
on:
  # mainから呼び出す
  workflow_call:
    inputs:
      new_tag:
        required: true
        type: string
      new_version:
        required: true
        type: string
      changelog:
        required: true
        type: string
    secrets:
      PLATFORMIO_AUTH_TOKEN:
        required: true

jobs:
  CreateRelease:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set version
        run: sed -i -e 's/[0-9]\+\.[0-9]\+\.[0-9]\+/${{ inputs.new_version }}/' library.properties library.json

      - name: Push version
        env:
          branch: "release/${{ inputs.new_tag }}"
        run: |
          git switch -c ${{ env.branch }}
          git add .
          git commit -m "Bump version: ${{ inputs.new_tag }}"
          git tag -a ${{ inputs.new_tag }} -m "Bump version: ${{ inputs.new_tag }}"
          git push -u origin ${{ env.branch }}
          git push origin ${{ inputs.new_tag }}

      - name: Create and merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: "release/${{ inputs.new_tag }}"
        run: |
          gh pr create --base ${GITHUB_REF_NAME} --head ${{ env.branch }} --assignee ${GITHUB_ACTOR} -l "bump version" \
             --title "Bump version: ${{ inputs.new_tag }}" --body 'Automated changes by [Bump Version](https://github.com/teruyamato0731/Chassis/actions/workflows/main.yml) GitHub action'
          gh pr merge ${{ env.branch }} --merge --delete-branch

      - uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/teruyamato0731/chassis-devcontainer
          push: never
          runCmd: pio pkg pack -o Chassis-${{ inputs.new_version }}.tar.gz && pio pkg publish --no-interactive
          env: |
            PLATFORMIO_AUTH_TOKEN=${{ secrets.PLATFORMIO_AUTH_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.new_tag }}
          body: ${{ inputs.changelog }}
          artifacts: Chassis-${{ inputs.new_version }}.tar.gz

      - name: Delete cache
        run: |
          curl -X PURGE https://camo.githubusercontent.com/b0dfa47fce01d3b2696fda450c451312795fb591036205ae07de1bdb47853981/68747470733a2f2f6261646765732e72656769737472792e706c6174666f726d696f2e6f72672f7061636b616765732f7465727579616d61746f303733312f6c6962726172792f436861737369732e737667
