name: CTest

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CTest:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target all --clean-first -j4

      - name: Test
        run:  |
          cd build
          ctest --rerun-failed --output-on-failure -j 4
