name: Doxygen Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch doxygen-awesome-css themes (true OR recursive)
      - name: set version
        run: echo "PROJECT_NUMBER = `git describe --tags --abbrev=0`" >> Doxyfile
      - name: Build
        uses: mattnotmitt/doxygen-action@v1.9.4
      - name : Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
