name: GoogleTest

on:
  push:
    branches:
      - main
      - 'feat/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GoogleTest:
    # 二重実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch GoogleTest themes (true OR recursive)

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target all --clean-first -j4

      - name: Test
        run: |
          cd build
          ctest --rerun-failed --output-on-failure -j 4
