name: CI
on:
  push:
    branches:
      - main
      - 'feat/**'
      - ci
  # 手動実行を許可する
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test
    uses: ./.github/workflows/unit-test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  bump-version:
    name: Bump Version  # バージョンをあげる
    if: ${{ github.ref_name == 'main' || github.ref_name == 'ci' }}  # mainブランチのみ Bump
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      release_type: ${{ steps.tag-version.outputs.release_type }}
      previous_tag: ${{ steps.tag-version.outputs.previous_tag }}
      new_tag: ${{ steps.tag-version.outputs.new_tag }}
      new_version: ${{ steps.tag-version.outputs.new_version }}
      changelog: ${{ steps.tag-version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          dry_run: true  # tagはRelease作成時つける

  devcontainers-ci:
    name: build devcontainer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/teruyamato0731/chassis-devcontainer
          cacheFrom: ghcr.io/teruyamato0731/chassis-devcontainer
          refFilterForPush: 'refs/heads/main'
          skipContainerUserIdUpdate: true

  create-release:
    name: Create Release  # Releaseを作成
    needs: [unit-test, bump-version, devcontainers-ci]
    if: ${{ github.ref_name == 'main' && needs.unit-test.result == 'success' && needs.bump-version.outputs.release_type != false }}
    # mainブランチのみ unit-test成功時のみ バージョンがあがるときのみ
    uses: ./.github/workflows/create-release.yml
    with:
      new_tag: ${{ needs.bump-version.outputs.new_tag }}
      new_version: ${{ needs.bump-version.outputs.new_version }}
      changelog: ${{ needs.bump-version.outputs.changelog }}
    secrets:
      PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

  pages-deploy:
    name: Doxygen Deploy Action  # github.ioにデプロイ
    needs: [unit-test, bump-version, devcontainers-ci]
    # mainブランチのみ bump-version成功時のみ (unit-testの成否によらずデプロイする)
    if: ${{ (github.ref_name == 'main' || github.ref_name == 'ci') && needs.bump-version.result == 'success' }}
    uses: ./.github/workflows/doxygen-gh-pages.yml
    with:
      # unit-test成功かつneeds.unit-test.outputs.release_type != false のとき new_tag
      # unit-test失敗 Bumpなしのとき previous_tag
      project_version: ${{ (needs.unit-test.result == 'success' && needs.bump-version.outputs.release_type != false &&
                            needs.bump-version.outputs.new_tag) || needs.bump-version.outputs.previous_tag }}
